### ISSUE TITLE
p0 reference solution does not work on ARM64

### ISSUE THREAD

**Issue by laurelmay** [JMU-CS/c-test-framework#6]
The reference solution (and some of the sample submissions) for p0 do not work on ARM64. The issue seems to be in the following section of code in main.c:

```c
    char c;
    while ((c = getopt(argc, argv, "gf:c:")) != -1) {
        switch (c) {

            case 'g': goodbye = true; hello = false;                    break;
            case 'f':    fact = true; hello = false; fact_num = optarg; break;
            case 'c':     cat = true; hello = false;   cat_fn = optarg; break;

            default:
                printf("Invalid argument.\n");
                return EXIT_FAILURE;
        }
    }
```

No matter what command line arguments are passed to `intro`, it always prints "Invalid argument."

The issue seems to be that after the call to `getopt(3)`, `c` holds the value 255. While this should be the same as -1, the comparison seems to evaluate to true, so the loop body executes. The default branch then matches and the program terminates.

Since `getopt(3)` returns an `int`, I am curious if it is getting truncated to `sizeof(char)` for the assignment and then `c` is zero-extended during the comparison. Doing a zero-extension would be odd, but it's the only explanation I've been able to think of. The output of `gcc -S -g -O0 main.c` is attached as `[main.txt](https://github.com/JMU-CS/c-test-framework/files/2630820/main.txt) (GitHub apparently really cared about the file extension being one of the supported ones). I don't know ARM assembly well-enough to know what's happening.

Changing the declaration of `c` to `int c` seems to fix the issue.
Interestingly, so does
```c
while ((c = getopt(argc, argv, "gf:c:")) != (char) -1) {
```

I am happy to submit a PR to fix this. Are there any places other than the reference solution and the sample student submissions for p0 that would need to be adjusted?

**Comment by lam2mo** [comment]
Thanks for finding this! I am not aware of any other locations that need to be fixed. Everything else is generated from those locations by scripts.
